SELECT ID, Nombre FROM HABITAT;
SELECT Nombre FROM ANIMALES WHERE IDHabitat = 10;

SELECT Nombre AS cuidador FROM CUIDADOR ORDER BY Nombre;

SELECT Nombre, IDEspecie FROM ANIMALES WHERE IDHabitat = 19;

