--INNER JOIN.
--
SELECT E.NOMBRE AS ESPECIE,EC.NOMBRE AS ESTADO_CONSERVACION,FA.NOMBRECOMUN
FROM ESPECIE E
INNER JOIN ESTADO_CONSERVACION EC ON E.IDESTADOCONSERVACION = EC.ID
INNER JOIN FAMILIA FA ON E.IDFAMILIA = FA.ID
WHERE E.NOMBRE LIKE '%Delfín%';
